Rama tarea 2
lbenet/2023-2_TSFC1 pull request #5
Opened 2023-05-09 02:00 UTC by OscarAlvaradoM

En el notebook de la tarea 2 se tienen todo hasta el primer inciso del Ejercicio 3, sí se converge a un valor de la sucesión fn, pero no estoy seguro si sea correcto. Faltaría el segundo inciso de dicho ejercicio y documentar todo lo que se hizo.

2023-05-09 18:18 UTC, lbenet requested changes
Gracias por enviar tu tarea. Te envío así los comentarios, ya que es más difícil marcar las cosas en los .ipynb's...

Lo primero que veo es que hay demasiadas cosas que estás tratando de modificar/subir, y que no tienen que ser modificadas/subidas. Entonces, empiezo por sugerir que *quites* todos los cambios a los archivos: que están en el directorio `clases/` (ahí cambiaste 6 archivos), que *no* subas lo que está en `tareas/.ipynb_checkpoints/` (directorio y un archivo), y que no modifiques ninguno de los archivos que están en `/tareas` (3 archivos) excepto los que están en tu directorio. En cuanto a tu directorio, no subas lo que hay bajo el directorio `oscar/.ipynb_checkpoints/`.  (Creo que todo esto se originó en el hecho de que cuando creaste la nueva rama, no tenías la última versión del repo en tu máquina...)

Tomando todo esto en cuenta, el punto es que sólo debes subir `tareas/oscar/duales.jl` y (por el momento) `tareas/oscar/tarea2.ipynb` (aunque como .jl para usar con `Literate`).

En cuanto a la tarea en sí, las gráficas que subiste del ejercicio 1 corresponden al mapeo $Q_x(x)=x^2-0.5$, y no al caso $Q_x(x)=x^2-2$; checa el enunciado del ejercicio. Una vez dicho esto, excepto por la conclusión, que *puede* cambiar, me parece que tienes lo necesario para hacer el ejercicio bien. 

En cuanto al ejercicio 2, los dos primeros incisos se ven bien. Por otra parte, el inciso (c) pide *todos* los puntos fijos (periodo 1); el que obtuviste es correcto, pero de hecho hay dos puntos fijos de periodo 1 (que obtuviste en (d)!). El inciso (d) lo tienes bien, excepto que incluíste *ambos* puntos fijos; sugiero que los filtres de alguna manera. Respecto al inciso (e), está bien, y efectivamente mostraste que son linealmente estables. Creo que puedes decir algo más (ya que su derivadas es 0!)... 

En este ejercicio tengo dos observaciones: (i) qué pasa con tu función `findroots` para `Q(x)=x^2 + 1`? (ii) En la celda [12], donde defines la función `findroots`, la observación es que, dado que `x_0` es un `Float64`, entonces *definas* a `roots` como `roots = Float64[]`; esto evita que el vector con todas las raíces sea tipo `Any`...

Del tercer ejercicio, lo que llevas del primer inciso lo veo **muy bien**; tu resultado, es correcto a 6 decimales!! Creo que la gráfica no te va a mostrar mucho, sólo que "el valor" de $f_n$ tienden a una constante! Ahora falta el inciso 2.

Resumiendo: veo muy bien la tarea, y sólo faltan un par de detalles...

2023-05-11 00:56 UTC, lbenet commented
Creo que ahora estás borrando de más! De hecho, creo que estás borrando todo lo que hay en el directorio clases/!

Mi sugerencia es que trates de rescatar los cambios al archivo tareas/oscar/tarea2.jl, incluyendo donde pusiste lo de diferenciación automática. Que desde `main` crees otro branch, donde sólo pones esos dos archivos, y vuelvas a hacer un PR... Este PR, lo podemos borrar más tarde...

No sé si mi sugerencia está clara?

2023-05-11 01:03 UTC, OscarAlvaradoM commented
Ya entiendo! Creí que eliminando esos archivos del PR sólo se quitarían de la solicitud, pero en realidad los estaría borrando del `main`, no?
A ver, intento esto que me dices y lo subo de nuevo.

2023-05-11 06:01 UTC, Julian-RC commented
Cierro este pull request ya que se ha abierto uno nuevo con la tarea 2 y sin modificar archivos de la clase c:

2023-05-11 06:01 UTC, closed without merging